using System.Text;
using Microsoft.CodeAnalysis;

namespace TaskTupleAwaiter.Generator;

[Generator]
public sealed class TaskTupleExtensionsGenerator : IIncrementalGenerator
{
	const int MaxArity = 16;

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		// Feature-detect ConfigureAwaitOptions by checking whether the type actually
		// exists in the compilation's referenced assemblies, rather than sniffing a
		// preprocessor symbol. This correctly handles cases where someone compiles
		// against .NET 8+ without the SDK-injected NET8_0_OR_GREATER define.
		var hasAwaitOptionsProvider = context.CompilationProvider
			.Select(static (compilation, _) =>
				compilation.GetTypeByMetadataName("System.Threading.Tasks.ConfigureAwaitOptions") is not null);

		context.RegisterSourceOutput(
			hasAwaitOptionsProvider,
			static (ctx, hasAwaitOptions) =>
				ctx.AddSource("TaskTupleExtensions.g.cs", GenerateSource(hasAwaitOptions)));
	}

	static string GenerateSource(bool hasAwaitOptions)
	{
		StringBuilder sb = new();

		sb.AppendCSharp(
			"""
			// <auto-generated/>
			using System.Runtime.CompilerServices;
			using System.Security;

			#pragma warning disable IDE0130 // Namespace does not match folder structure
			namespace System.Threading.Tasks;
			#pragma warning restore IDE0130 // Namespace does not match folder structure

			/// <summary>
			/// Provides extension methods for working with tuples of tasks, enabling awaiting and configuring await behavior
			/// for multiple tasks in a tuple.
			/// </summary>
			/// <remarks>
			/// Ported from jnm2: https://gist.github.com/jnm2/3660db29457d391a34151f764bfe6ef7
			/// </remarks>
			public static class TaskTupleExtensions
			{

			""");

		AppendTypedArity1(sb, hasAwaitOptions);
		for (var arity = 2; arity <= MaxArity; arity++)
			AppendTypedArity(sb, arity, hasAwaitOptions);
		AppendNonGenericSection(sb, hasAwaitOptions);

		sb.AppendCSharp("}");
		return sb.ToString();
	}

	// ── Typed Task<T> ─────────────────────────────────────────────────────

	static void AppendTypedArity1(StringBuilder sb, bool hasAwaitOptions)
	{
		sb.AppendCSharp(
			"""
			#region (Task<T1>)

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static TaskAwaiter<T1> GetAwaiter<T1>(this ValueTuple<Task<T1>> tasks) =>
				tasks.Item1.GetAwaiter();

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static ConfiguredTaskAwaitable<T1> ConfigureAwait<T1>(this ValueTuple<Task<T1>> tasks, bool continueOnCapturedContext) =>
				tasks.Item1.ConfigureAwait(continueOnCapturedContext);

			""");

		if (hasAwaitOptions)
			sb.AppendCSharp(
				"""
				/// <summary>This type and its members are intended for use by the compiler.</summary>
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static ConfiguredTaskAwaitable<T1> ConfigureAwait<T1>(this ValueTuple<Task<T1>> tasks, ConfigureAwaitOptions options) =>
					tasks.Item1.ConfigureAwait(options);

				""");

		sb.AppendCSharp(
			"""
			#endregion

			""");
	}

	static void AppendTypedArity(StringBuilder sb, int arity, bool hasAwaitOptions)
	{
		var tp = TypeParams(arity);
		var tupleType = TypedTaskTupleType(arity);
		var optionsType = hasAwaitOptions ? "ConfigureAwaitOptions" : "bool";
		var configureAwaitBoolArg = hasAwaitOptions
			? "continueOnCapturedContext ? ConfigureAwaitOptions.ContinueOnCapturedContext : ConfigureAwaitOptions.None"
			: "continueOnCapturedContext";

		sb.AppendCSharp(
			$"""
			#region (Task<T1>..Task<T{arity}>)

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static TupleTaskAwaiter<{tp}> GetAwaiter<{tp}>(this {tupleType} tasks) =>
				new(tasks);

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static TupleConfiguredTaskAwaitable<{tp}> ConfigureAwait<{tp}>(this {tupleType} tasks, bool continueOnCapturedContext) =>
				new(tasks, {configureAwaitBoolArg});

			""");

		if (hasAwaitOptions)
			sb.AppendCSharp(
				$"""
				/// <summary>This type and its members are intended for use by the compiler.</summary>
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static TupleConfiguredTaskAwaitable<{tp}> ConfigureAwait<{tp}>(this {tupleType} tasks, ConfigureAwaitOptions options) =>
					new(tasks, options);

				""");

		AppendTupleTaskAwaiterStruct(sb, arity, tp, tupleType);

		AppendTupleConfiguredTaskAwaitableStruct(sb, arity, tp, tupleType, optionsType);

		sb.AppendCSharp(
			"""
			#endregion

			""");
	}

	static void AppendTupleTaskAwaiterStruct(StringBuilder sb, int arity, string tp, string tupleType) => sb.AppendCSharp(
		$$"""
		/// <summary>This type and its members are intended for use by the compiler.</summary>
		public readonly struct TupleTaskAwaiter<{{tp}}> : ICriticalNotifyCompletion
		{
			readonly {{tupleType}} _tasks;
			readonly TaskAwaiter _whenAllAwaiter;

			internal TupleTaskAwaiter({{tupleType}} tasks)
			{
				_tasks = tasks;
				_whenAllAwaiter = Task.WhenAll({{Items(arity)}}).GetAwaiter();
			}

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public bool IsCompleted
			{
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				get => _whenAllAwaiter.IsCompleted;
			}

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public void OnCompleted(Action continuation) =>
				_whenAllAwaiter.OnCompleted(continuation);

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			[SecurityCritical]
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public void UnsafeOnCompleted(Action continuation) =>
				_whenAllAwaiter.UnsafeOnCompleted(continuation);

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public ({{tp}}) GetResult()
			{
				_whenAllAwaiter.GetResult();
				return ({{Results(arity)}});
			}
		}

		""");

	static void AppendTupleConfiguredTaskAwaitableStruct(StringBuilder sb, int arity, string tp,
		string tupleType, string optionsType) => sb.AppendCSharp(
		$$"""
		/// <summary>This type and its members are intended for use by the compiler.</summary>
		public readonly struct TupleConfiguredTaskAwaitable<{{tp}}>
		{
			readonly {{tupleType}} _tasks;
			readonly {{optionsType}} _options;

			internal TupleConfiguredTaskAwaitable({{tupleType}} tasks, {{optionsType}} options)
			{
				_tasks = tasks;
				_options = options;
			}

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public Awaiter GetAwaiter() =>
				new(_tasks, _options);

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public readonly struct Awaiter : ICriticalNotifyCompletion
			{
				readonly {{tupleType}} _tasks;
				readonly ConfiguredTaskAwaitable.ConfiguredTaskAwaiter _whenAllAwaiter;

				internal Awaiter({{tupleType}} tasks, {{optionsType}} options)
				{
					_tasks = tasks;
					_whenAllAwaiter = Task.WhenAll({{Items(arity)}}).ConfigureAwait(options).GetAwaiter();
				}

				/// <summary>This type and its members are intended for use by the compiler.</summary>
				public bool IsCompleted
				{
					[MethodImpl(MethodImplOptions.AggressiveInlining)]
					get => _whenAllAwaiter.IsCompleted;
				}

				/// <summary>This type and its members are intended for use by the compiler.</summary>
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public void OnCompleted(Action continuation) =>
					_whenAllAwaiter.OnCompleted(continuation);

				/// <summary>This type and its members are intended for use by the compiler.</summary>
				[SecurityCritical]
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public void UnsafeOnCompleted(Action continuation) =>
					_whenAllAwaiter.UnsafeOnCompleted(continuation);

				/// <summary>This type and its members are intended for use by the compiler.</summary>
				public ({{tp}}) GetResult()
				{
					_whenAllAwaiter.GetResult();
					return ({{Results(arity)}});
				}
			}
		}
		
		""");

	// ── Non-generic Task ──────────────────────────────────────────────────

	static void AppendNonGenericSection(StringBuilder sb, bool hasAwaitOptions)
	{
		sb.AppendCSharp(
			"""
			#region Task

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static TaskAwaiter GetAwaiter(this ValueTuple<Task> tasks) =>
				tasks.Item1.GetAwaiter();

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			[MethodImpl(MethodImplOptions.AggressiveInlining)]
			public static ConfiguredTaskAwaitable ConfigureAwait(this ValueTuple<Task> tasks, bool continueOnCapturedContext) =>
				tasks.Item1.ConfigureAwait(continueOnCapturedContext);

			""");

		if (hasAwaitOptions)
			sb.AppendCSharp(
				"""
				/// <summary>This type and its members are intended for use by the compiler.</summary>
				[MethodImpl(MethodImplOptions.AggressiveInlining)]
				public static ConfiguredTaskAwaitable ConfigureAwait(this ValueTuple<Task> tasks, ConfigureAwaitOptions options) =>
					tasks.Item1.ConfigureAwait(options);

				""");

		for (var arity = 2; arity <= MaxArity; arity++)
		{
			AppendNonGenericArity(sb, arity, hasAwaitOptions);
		}

		sb.AppendCSharp(
			"""
			#endregion

			""");
	}

	static void AppendNonGenericArity(StringBuilder sb, int arity, bool hasAwaitOptions)
	{
		var tupleType = NonGenericTaskTupleType(arity);

		sb.AppendCSharp(
			$"""
			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public static TaskAwaiter GetAwaiter(this {tupleType} tasks) =>
				Task.WhenAll({Items(arity)}).GetAwaiter();

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public static ConfiguredTaskAwaitable ConfigureAwait(this {tupleType} tasks, bool continueOnCapturedContext) =>
				Task.WhenAll({Items(arity)}).ConfigureAwait(continueOnCapturedContext);
				
			""");

		if (!hasAwaitOptions) return;

		sb.AppendCSharp(
			$"""
			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public static ConfiguredTaskAwaitable ConfigureAwait(this {tupleType} tasks, ConfigureAwaitOptions options) =>
				Task.WhenAll({Items(arity)}).ConfigureAwait(options);

			""");
	}

	// ── String helpers ────────────────────────────────────────────────────

	static string TypeParams(int arity) =>
		string.Join(", ", Enumerable.Range(1, arity).Select(i => $"T{i}"));

	static string TypedTaskTupleType(int arity) =>
		$"({string.Join(", ", Enumerable.Range(1, arity).Select(i => $"Task<T{i}>"))})";

	static string NonGenericTaskTupleType(int arity) =>
		$"({string.Join(", ", Enumerable.Repeat("Task", arity))})";

	// Returns the generated WhenAll argument list in bracket form.
	// Overload binding is determined by library target framework:
	// net10.0 binds Task.WhenAll(ReadOnlySpan<Task>) (stack-allocated buffer),
	// while netstandard2.0/net462/net8.0 bind Task.WhenAll(params Task[])
	// (array allocation, same IL shape as before this change). The library does
	// not ship a net9.0 asset, so .NET 9 consumers pick the net8.0 asset.
	static string Items(int arity) =>
		$"[{string.Join(", ", Enumerable.Range(1, arity).Select(i => $"tasks.Item{i}"))}]";

	static string Results(int arity) =>
		string.Join(", ", Enumerable.Range(1, arity).Select(i => $"_tasks.Item{i}.Result"));
}
