using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace TaskTupleAwaiter.Generator;

[Generator]
public sealed class TaskTupleExtensionsGenerator : IIncrementalGenerator
{
	private const int MaxArity = 16;

	public void Initialize(IncrementalGeneratorInitializationContext context) =>
		context.RegisterSourceOutput(
			context.ParseOptionsProvider,
			static (ctx, parseOptions) =>
			{
				var isNet8OrGreater = parseOptions is CSharpParseOptions csOptions &&
									  csOptions.PreprocessorSymbolNames.Contains("NET8_0_OR_GREATER");
				ctx.AddSource("TaskTupleExtensions.g.cs", GenerateSource(isNet8OrGreater));
			});

	private static string GenerateSource(bool isNet8OrGreater)
	{
		StringBuilder sb = new();

		sb.AppendLine("// <auto-generated/>");
		sb.AppendLine("using System.Runtime.CompilerServices;");
		sb.AppendLine("using System.Security;");
		sb.AppendLine();
		sb.AppendLine("#pragma warning disable IDE0130 // Namespace does not match folder structure");
		sb.AppendLine("namespace System.Threading.Tasks;");
		sb.AppendLine("#pragma warning restore IDE0130 // Namespace does not match folder structure");
		sb.AppendLine();
		sb.AppendLine("/// <summary>");
		sb.AppendLine(
			"/// Provides extension methods for working with tuples of tasks, enabling awaiting and configuring await behavior");
		sb.AppendLine("/// for multiple tasks in a tuple.");
		sb.AppendLine("/// </summary>");
		sb.AppendLine("/// <remarks>");
		sb.AppendLine("/// Ported from jnm2: https://gist.github.com/jnm2/3660db29457d391a34151f764bfe6ef7");
		sb.AppendLine("/// </remarks>");
		sb.AppendLine("public static class TaskTupleExtensions");
		sb.AppendLine("{");

		AppendTypedArity1(sb, isNet8OrGreater);
		for (var arity = 2; arity <= MaxArity; arity++)
			AppendTypedArity(sb, arity, isNet8OrGreater);

		AppendNonGenericSection(sb, isNet8OrGreater);

		sb.AppendLine("}");
		return sb.ToString();
	}

	// ── Typed Task<T> ─────────────────────────────────────────────────────

	private static void AppendTypedArity1(StringBuilder sb, bool isNet8OrGreater)
	{
		sb.AppendLine("\t#region (Task<T1>)");
		sb.AppendLine();
		sb.AppendLine("\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine("\tpublic static TaskAwaiter<T1> GetAwaiter<T1>(this ValueTuple<Task<T1>> tasks) =>");
		sb.AppendLine("\t\ttasks.Item1.GetAwaiter();");
		sb.AppendLine();
		sb.AppendLine("\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine(
			"\tpublic static ConfiguredTaskAwaitable<T1> ConfigureAwait<T1>(this ValueTuple<Task<T1>> tasks, bool continueOnCapturedContext) =>");
		sb.AppendLine("\t\ttasks.Item1.ConfigureAwait(continueOnCapturedContext);");

		if (isNet8OrGreater)
		{
			sb.AppendLine();
			sb.AppendLine("\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
			sb.AppendLine(
				"\tpublic static ConfiguredTaskAwaitable<T1> ConfigureAwait<T1>(this ValueTuple<Task<T1>> tasks, ConfigureAwaitOptions options) =>");
			sb.AppendLine("\t\ttasks.Item1.ConfigureAwait(options);");
		}

		sb.AppendLine();
		sb.AppendLine("\t#endregion");
		sb.AppendLine();
	}

	private static void AppendTypedArity(StringBuilder sb, int arity, bool isNet8OrGreater)
	{
		var tp = TypeParams(arity);
		var tupleType = TypedTaskTupleType(arity);
		var optionsType = isNet8OrGreater ? "ConfigureAwaitOptions" : "bool";
		var configureAwaitBoolArg = isNet8OrGreater
			? "continueOnCapturedContext ? ConfigureAwaitOptions.ContinueOnCapturedContext : ConfigureAwaitOptions.None"
			: "continueOnCapturedContext";

		sb.AppendLine($"\t#region (Task<T1>..Task<T{arity}>)");
		sb.AppendLine();
		sb.AppendLine("\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine($"\tpublic static TupleTaskAwaiter<{tp}> GetAwaiter<{tp}>(this {tupleType} tasks) =>");
		sb.AppendLine("\t\tnew(tasks);");
		sb.AppendLine();
		sb.AppendLine("\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine(
			$"\tpublic static TupleConfiguredTaskAwaitable<{tp}> ConfigureAwait<{tp}>(this {tupleType} tasks, bool continueOnCapturedContext) =>");
		sb.AppendLine($"\t\tnew(tasks, {configureAwaitBoolArg});");

		if (isNet8OrGreater)
		{
			sb.AppendLine();
			sb.AppendLine("\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
			sb.AppendLine(
				$"\tpublic static TupleConfiguredTaskAwaitable<{tp}> ConfigureAwait<{tp}>(this {tupleType} tasks, ConfigureAwaitOptions options) =>");
			sb.AppendLine("\t\tnew(tasks, options);");
		}

		sb.AppendLine();
		AppendTupleTaskAwaiterStruct(sb, arity, tp, tupleType);
		sb.AppendLine();
		AppendTupleConfiguredTaskAwaitableStruct(sb, arity, tp, tupleType, optionsType);
		sb.AppendLine();
		sb.AppendLine("\t#endregion");
		sb.AppendLine();
	}

	private static void AppendTupleTaskAwaiterStruct(StringBuilder sb, int arity, string tp, string tupleType)
	{
		sb.AppendLine("\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine($"\tpublic readonly record struct TupleTaskAwaiter<{tp}> : ICriticalNotifyCompletion");
		sb.AppendLine("\t{");
		sb.AppendLine($"\t\tprivate readonly {tupleType} _tasks;");
		sb.AppendLine("\t\tprivate readonly TaskAwaiter _whenAllAwaiter;");
		sb.AppendLine();
		sb.AppendLine($"\t\tinternal TupleTaskAwaiter({tupleType} tasks)");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\t_tasks = tasks;");
		sb.AppendLine($"\t\t\t_whenAllAwaiter = Task.WhenAll({Items(arity)}).GetAwaiter();");
		sb.AppendLine("\t\t}");
		sb.AppendLine();
		sb.AppendLine("\t\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine("\t\tpublic bool IsCompleted => _whenAllAwaiter.IsCompleted;");
		sb.AppendLine();
		sb.AppendLine("\t\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine("\t\tpublic void OnCompleted(Action continuation) => _whenAllAwaiter.OnCompleted(continuation);");
		sb.AppendLine();
		sb.AppendLine("\t\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine("\t\t[SecurityCritical]");
		sb.AppendLine(
			"\t\tpublic void UnsafeOnCompleted(Action continuation) => _whenAllAwaiter.UnsafeOnCompleted(continuation);");
		sb.AppendLine();
		sb.AppendLine("\t\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine($"\t\tpublic ({tp}) GetResult()");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\t_whenAllAwaiter.GetResult();");
		sb.AppendLine($"\t\t\treturn ({Results(arity)});");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
	}

	private static void AppendTupleConfiguredTaskAwaitableStruct(StringBuilder sb, int arity, string tp,
		string tupleType, string optionsType)
	{
		sb.AppendLine("\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine($"\tpublic readonly record struct TupleConfiguredTaskAwaitable<{tp}>");
		sb.AppendLine("\t{");
		sb.AppendLine($"\t\tprivate readonly {tupleType} _tasks;");
		sb.AppendLine($"\t\tprivate readonly {optionsType} _options;");
		sb.AppendLine();
		sb.AppendLine($"\t\tinternal TupleConfiguredTaskAwaitable({tupleType} tasks, {optionsType} options)");
		sb.AppendLine("\t\t{");
		sb.AppendLine("\t\t\t_tasks = tasks;");
		sb.AppendLine("\t\t\t_options = options;");
		sb.AppendLine("\t\t}");
		sb.AppendLine();
		sb.AppendLine("\t\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine("\t\tpublic Awaiter GetAwaiter() =>");
		sb.AppendLine("\t\t\tnew(_tasks, _options);");
		sb.AppendLine();
		sb.AppendLine("\t\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine("\t\tpublic readonly record struct Awaiter : ICriticalNotifyCompletion");
		sb.AppendLine("\t\t{");
		sb.AppendLine($"\t\t\tprivate readonly {tupleType} _tasks;");
		sb.AppendLine("\t\t\tprivate readonly ConfiguredTaskAwaitable.ConfiguredTaskAwaiter _whenAllAwaiter;");
		sb.AppendLine();
		sb.AppendLine($"\t\t\tinternal Awaiter({tupleType} tasks, {optionsType} options)");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\t_tasks = tasks;");
		sb.AppendLine($"\t\t\t\t_whenAllAwaiter = Task.WhenAll({Items(arity)}).ConfigureAwait(options).GetAwaiter();");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine();
		sb.AppendLine("\t\t\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine("\t\t\tpublic bool IsCompleted => _whenAllAwaiter.IsCompleted;");
		sb.AppendLine();
		sb.AppendLine("\t\t\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine(
			"\t\t\tpublic void OnCompleted(Action continuation) => _whenAllAwaiter.OnCompleted(continuation);");
		sb.AppendLine();
		sb.AppendLine("\t\t\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine("\t\t\t[SecurityCritical]");
		sb.AppendLine(
			"\t\t\tpublic void UnsafeOnCompleted(Action continuation) => _whenAllAwaiter.UnsafeOnCompleted(continuation);");
		sb.AppendLine();
		sb.AppendLine("\t\t\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine($"\t\t\tpublic ({tp}) GetResult()");
		sb.AppendLine("\t\t\t{");
		sb.AppendLine("\t\t\t\t_whenAllAwaiter.GetResult();");
		sb.AppendLine($"\t\t\t\treturn ({Results(arity)});");
		sb.AppendLine("\t\t\t}");
		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
	}

	// ── Non-generic Task ──────────────────────────────────────────────────

	private static void AppendNonGenericSection(StringBuilder sb, bool isNet8OrGreater)
	{
		sb.AppendLine("\t#region Task");
		sb.AppendLine();
		sb.AppendLine("\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine("\tpublic static TaskAwaiter GetAwaiter(this ValueTuple<Task> tasks) =>");
		sb.AppendLine("\t\ttasks.Item1.GetAwaiter();");
		sb.AppendLine();
		sb.AppendLine("\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine(
			"\tpublic static ConfiguredTaskAwaitable ConfigureAwait(this ValueTuple<Task> tasks, bool continueOnCapturedContext) =>");
		sb.AppendLine("\t\ttasks.Item1.ConfigureAwait(continueOnCapturedContext);");

		if (isNet8OrGreater)
		{
			sb.AppendLine();
			sb.AppendLine("\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
			sb.AppendLine(
				"\tpublic static ConfiguredTaskAwaitable ConfigureAwait(this ValueTuple<Task> tasks, ConfigureAwaitOptions options) =>");
			sb.AppendLine("\t\ttasks.Item1.ConfigureAwait(options);");
		}

		for (var arity = 2; arity <= MaxArity; arity++)
		{
			sb.AppendLine();
			AppendNonGenericArity(sb, arity, isNet8OrGreater);
		}

		sb.AppendLine();
		sb.AppendLine("\t#endregion");
	}

	private static void AppendNonGenericArity(StringBuilder sb, int arity, bool isNet8OrGreater)
	{
		var tupleType = NonGenericTaskTupleType(arity);

		sb.AppendLine("\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine($"\tpublic static TaskAwaiter GetAwaiter(this {tupleType} tasks) =>");
		sb.AppendLine($"\t\tTask.WhenAll({Items(arity)}).GetAwaiter();");
		sb.AppendLine();
		sb.AppendLine("\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine(
			$"\tpublic static ConfiguredTaskAwaitable ConfigureAwait(this {tupleType} tasks, bool continueOnCapturedContext) =>");
		sb.AppendLine($"\t\tTask.WhenAll({Items(arity)}).ConfigureAwait(continueOnCapturedContext);");

		if (!isNet8OrGreater) return;
		sb.AppendLine();
		sb.AppendLine("\t/// <summary>This type and its members are intended for use by the compiler.</summary>");
		sb.AppendLine(
			$"\tpublic static ConfiguredTaskAwaitable ConfigureAwait(this {tupleType} tasks, ConfigureAwaitOptions options) =>");
		sb.AppendLine($"\t\tTask.WhenAll({Items(arity)}).ConfigureAwait(options);");
	}

	// ── String helpers ────────────────────────────────────────────────────

	private static string TypeParams(int arity) =>
		string.Join(", ", Enumerable.Range(1, arity).Select(i => $"T{i}"));

	private static string TypedTaskTupleType(int arity) =>
		"(" + string.Join(", ", Enumerable.Range(1, arity).Select(i => $"Task<T{i}>")) + ")";

	private static string NonGenericTaskTupleType(int arity) =>
		"(" + string.Join(", ", Enumerable.Repeat("Task", arity)) + ")";

	private static string Items(int arity) =>
		string.Join(", ", Enumerable.Range(1, arity).Select(i => $"tasks.Item{i}"));

	private static string Results(int arity) =>
		string.Join(", ", Enumerable.Range(1, arity).Select(i => $"_tasks.Item{i}.Result"));
}
