using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace TaskTupleAwaiter.Generator;

[Generator]
public sealed class TaskTupleExtensionsGenerator : IIncrementalGenerator
{
	private const int MaxArity = 16;

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var hasAwaitOptionsProvider = context.ParseOptionsProvider
			.Select(
				static (options, _) =>
				{
					if (options is CSharpParseOptions csharpOptions)
					{
						// Assume NET8_0_OR_GREATER (or compatible) implies ConfigureAwaitOptions is available.
						foreach (var symbol in csharpOptions.PreprocessorSymbolNames)
						{
							if (string.Equals(symbol, "NET8_0_OR_GREATER", System.StringComparison.Ordinal))
							{
								return true;
							}
						}
					}

					return false;
				});

		context.RegisterSourceOutput(
			hasAwaitOptionsProvider,
			static (ctx, hasAwaitOptions) =>
			{
				ctx.AddSource("TaskTupleExtensions.g.cs", GenerateSource(hasAwaitOptions));
			});
	}

	private static string GenerateSource(bool hasAwaitOptions)
	{
		StringBuilder sb = new();

		sb.AppendLine(
			"""
			// <auto-generated/>
			using System.Runtime.CompilerServices;
			using System.Security;

			#pragma warning disable IDE0130 // Namespace does not match folder structure
			namespace System.Threading.Tasks;
			#pragma warning restore IDE0130 // Namespace does not match folder structure

			/// <summary>
			/// Provides extension methods for working with tuples of tasks, enabling awaiting and configuring await behavior
			/// for multiple tasks in a tuple.
			/// </summary>
			/// <remarks>
			/// Ported from jnm2: https://gist.github.com/jnm2/3660db29457d391a34151f764bfe6ef7
			/// </remarks>
			public static class TaskTupleExtensions
			{

			""");

		AppendTypedArity1(sb, hasAwaitOptions);
		for (var arity = 2; arity <= MaxArity; arity++)
			AppendTypedArity(sb, arity, hasAwaitOptions);
		AppendNonGenericSection(sb, hasAwaitOptions);

		sb.AppendLine("}");
		return sb.ToString();
	}

	// ── Typed Task<T> ─────────────────────────────────────────────────────

	private static void AppendTypedArity1(StringBuilder sb, bool hasAwaitOptions)
	{
		sb.AppendLine(
			"""
			#region (Task<T1>)

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public static TaskAwaiter<T1> GetAwaiter<T1>(this ValueTuple<Task<T1>> tasks) =>
				tasks.Item1.GetAwaiter();

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public static ConfiguredTaskAwaitable<T1> ConfigureAwait<T1>(this ValueTuple<Task<T1>> tasks, bool continueOnCapturedContext) =>
				tasks.Item1.ConfigureAwait(continueOnCapturedContext);

			""");

		if (hasAwaitOptions)
			sb.AppendLine(
				"""
				/// <summary>This type and its members are intended for use by the compiler.</summary>
				public static ConfiguredTaskAwaitable<T1> ConfigureAwait<T1>(this ValueTuple<Task<T1>> tasks, ConfigureAwaitOptions options) =>
					tasks.Item1.ConfigureAwait(options);
					
				""");

		sb.AppendLine(
			"""
			#endregion

			""");
	}

	private static void AppendTypedArity(StringBuilder sb, int arity, bool hasAwaitOptions)
	{
		var tp = TypeParams(arity);
		var tupleType = TypedTaskTupleType(arity);
		var optionsType = hasAwaitOptions ? "ConfigureAwaitOptions" : "bool";
		var configureAwaitBoolArg = hasAwaitOptions
			? "continueOnCapturedContext ? ConfigureAwaitOptions.ContinueOnCapturedContext : ConfigureAwaitOptions.None"
			: "continueOnCapturedContext";

		sb.AppendLine(
			$"""
			#region (Task<T1>..Task<T{arity}>)

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public static TupleTaskAwaiter<{tp}> GetAwaiter<{tp}>(this {tupleType} tasks) =>
				new(tasks);

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public static TupleConfiguredTaskAwaitable<{tp}> ConfigureAwait<{tp}>(this {tupleType} tasks, bool continueOnCapturedContext) =>
				new(tasks, {configureAwaitBoolArg});

			""");

		if (hasAwaitOptions)
			sb.AppendLine(
				$"""
				/// <summary>This type and its members are intended for use by the compiler.</summary>
				public static TupleConfiguredTaskAwaitable<{tp}> ConfigureAwait<{tp}>(this {tupleType} tasks, ConfigureAwaitOptions options) =>
					new(tasks, options);

				""");

		AppendTupleTaskAwaiterStruct(sb, arity, tp, tupleType);

		AppendTupleConfiguredTaskAwaitableStruct(sb, arity, tp, tupleType, optionsType);

		sb.AppendLine(
			"""
			#endregion

			""");
	}

	private static void AppendTupleTaskAwaiterStruct(StringBuilder sb, int arity, string tp, string tupleType) => sb.AppendLine(
		$$"""
		/// <summary>This type and its members are intended for use by the compiler.</summary>
		public readonly record struct TupleTaskAwaiter<{{tp}}> : ICriticalNotifyCompletion
		{
			private readonly {{tupleType}} _tasks;
			private readonly TaskAwaiter _whenAllAwaiter;

			internal TupleTaskAwaiter({{tupleType}} tasks)
			{
				_tasks = tasks;
				_whenAllAwaiter = Task.WhenAll({{Items(arity)}}).GetAwaiter();
			}

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public bool IsCompleted =>
				_whenAllAwaiter.IsCompleted;

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public void OnCompleted(Action continuation) =>
				_whenAllAwaiter.OnCompleted(continuation);

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			[SecurityCritical]
			public void UnsafeOnCompleted(Action continuation) =>
				_whenAllAwaiter.UnsafeOnCompleted(continuation);

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public ({{tp}}) GetResult()
			{
				_whenAllAwaiter.GetResult();
				return ({{Results(arity)}});
			}
		}

		""");

	private static void AppendTupleConfiguredTaskAwaitableStruct(StringBuilder sb, int arity, string tp,
		string tupleType, string optionsType) => sb.AppendLine(
		$$"""
		/// <summary>This type and its members are intended for use by the compiler.</summary>
		public readonly record struct TupleConfiguredTaskAwaitable<{{tp}}>
		{
			private readonly {{tupleType}} _tasks;
			private readonly {{optionsType}} _options;

			internal TupleConfiguredTaskAwaitable({{tupleType}} tasks, {{optionsType}} options)
			{
				_tasks = tasks;
				_options = options;
			}

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public Awaiter GetAwaiter() =>
				new(_tasks, _options);

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public readonly record struct Awaiter : ICriticalNotifyCompletion
			{
				private readonly {{tupleType}} _tasks;
				private readonly ConfiguredTaskAwaitable.ConfiguredTaskAwaiter _whenAllAwaiter;

				internal Awaiter({{tupleType}} tasks, {{optionsType}} options)
				{
					_tasks = tasks;
					_whenAllAwaiter = Task.WhenAll({{Items(arity)}}).ConfigureAwait(options).GetAwaiter();
				}

				/// <summary>This type and its members are intended for use by the compiler.</summary>
				public bool IsCompleted => 
					_whenAllAwaiter.IsCompleted;

				/// <summary>This type and its members are intended for use by the compiler.</summary>
				public void OnCompleted(Action continuation) =>
					_whenAllAwaiter.OnCompleted(continuation);

				/// <summary>This type and its members are intended for use by the compiler.</summary>
				[SecurityCritical]
				public void UnsafeOnCompleted(Action continuation) =>
					_whenAllAwaiter.UnsafeOnCompleted(continuation);

				/// <summary>This type and its members are intended for use by the compiler.</summary>
				public ({{tp}}) GetResult()
				{
					_whenAllAwaiter.GetResult();
					return ({{Results(arity)}});
				}
			}
		}
		
		""");

	// ── Non-generic Task ──────────────────────────────────────────────────

	private static void AppendNonGenericSection(StringBuilder sb, bool hasAwaitOptions)
	{
		sb.AppendLine(
			"""
			#region Task

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public static TaskAwaiter GetAwaiter(this ValueTuple<Task> tasks) =>
				tasks.Item1.GetAwaiter();

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public static ConfiguredTaskAwaitable ConfigureAwait(this ValueTuple<Task> tasks, bool continueOnCapturedContext) =>
				tasks.Item1.ConfigureAwait(continueOnCapturedContext);

			""");

		if (hasAwaitOptions)
			sb.AppendLine(
				"""
				/// <summary>This type and its members are intended for use by the compiler.</summary>
				public static ConfiguredTaskAwaitable ConfigureAwait(this ValueTuple<Task> tasks, ConfigureAwaitOptions options) =>
					tasks.Item1.ConfigureAwait(options);

				""");

		for (var arity = 2; arity <= MaxArity; arity++)
		{
			AppendNonGenericArity(sb, arity, hasAwaitOptions);
		}

		sb.AppendLine(
			"""
			#endregion

			""");
	}

	private static void AppendNonGenericArity(StringBuilder sb, int arity, bool hasAwaitOptions)
	{
		var tupleType = NonGenericTaskTupleType(arity);

		sb.AppendLine(
			$"""
			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public static TaskAwaiter GetAwaiter(this {tupleType} tasks) =>
				Task.WhenAll({Items(arity)}).GetAwaiter();

			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public static ConfiguredTaskAwaitable ConfigureAwait(this {tupleType} tasks, bool continueOnCapturedContext) =>
				Task.WhenAll({Items(arity)}).ConfigureAwait(continueOnCapturedContext);
				
			""");

		if (!hasAwaitOptions) return;

		sb.AppendLine(
			$"""
			/// <summary>This type and its members are intended for use by the compiler.</summary>
			public static ConfiguredTaskAwaitable ConfigureAwait(this {tupleType} tasks, ConfigureAwaitOptions options) =>
				Task.WhenAll({Items(arity)}).ConfigureAwait(options);

			""");
	}

	// ── String helpers ────────────────────────────────────────────────────

	private static string TypeParams(int arity) =>
		string.Join(", ", Enumerable.Range(1, arity).Select(i => $"T{i}"));

	private static string TypedTaskTupleType(int arity) =>
		$"({string.Join(", ", Enumerable.Range(1, arity).Select(i => $"Task<T{i}>"))})";

	private static string NonGenericTaskTupleType(int arity) =>
		$"({string.Join(", ", Enumerable.Repeat("Task", arity))})";

	private static string Items(int arity) =>
		string.Join(", ", Enumerable.Range(1, arity).Select(i => $"tasks.Item{i}"));

	private static string Results(int arity) =>
		string.Join(", ", Enumerable.Range(1, arity).Select(i => $"_tasks.Item{i}.Result"));
}
